[tools]
# global tool versions go here
# you can set these with `mise use -g`
node = '20'
python = ['3.10', '3.11']
go = '1.21'

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
