#!/usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,git,zsh,yabai,skhd,sketchybar,gh,kitty,nvim,poetry"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES

# The 'bin' directory in different in that you don't want the entire directory linked 
echo "stow dir"  
stow -D bin
stow --no-folding bin

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

pushd ~/.dotfiles/personal
./stow
popd
