#!/usr/bin/env bash

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,tmux,git,zsh,yabai,skhd,sketchybar,gh,kitty,nvim,poetry,mise"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow --no-folding $folder
done
popd

pushd ~/.dotfiles/personal
./stow
popd
