[tools]
# global tool versions go here
# you can set these with `rtx use -g`
node = 'lts'
python = ['3.10', '3.11']

[settings]
# config files with these prefixes will be trusted by default
trusted_config_paths = [
    '~/personal',
    '~/work',
]
